#Data cleaning on two datas

In [ ]:
import pandas as pd
#import pandas

In [4]:
#import first data
data1=pd.read_excel("/content/2_HR_Cleaning_Practice.xlsx")

In [5]:
#get first 5 rows
data1.head()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
0,EMP-0152,Employee_151,Finance,4980.356928,38.0,Hybrid,5,MGR-4,2015-06-01
1,EMP-0754,Employee_753,HR,5988.381253,20.0,On-site,2,MGR-34,2017-01-23
2,EMP-1472,Employee_1471,Sales,3252.604294,30.0,Remote,1,MGR-24,2019-01-11
3,EMP-1232,Employee_1231,HR,4177.594228,6.0,Hybrid,5,MGR-7,2018-05-16
4,EMP-0022,Employee_21,Legal,273154.715607,35.0,Remote,1,MGR-13,2015-01-22

In [6]:
#get last 5 rows
data1.tail()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
2595,EMP-1723,Employee_1722,Legal,4452.919905,36.0,Remote,5,MGR-8,2019-09-19
2596,EMP-1861,Employee_1860,Legal,180876.613506,13.0,Remote,5,MGR-18,2020-02-04
2597,EMP-0821,Employee_820,HR,5607.862204,21.0,On-site,1,MGR-1,2017-03-31
2598,EMP-1069,Employee_1068,Sales,5129.528837,14.0,Hybrid,4,MGR-46,2017-12-04
2599,EMP-0209,Employee_208,Legal,5657.076068,NaN,Hybrid,2,MGR-45,2015-07-28

##Handelling Null values
-> find null values

-> fill or delete null values rows

In [7]:
#find null values
data1.isnull().sum()

Employee_ID            0
Full_Name              0
Department             0
Monthly_Salary         0
Years_Exp            326
Office_Location        0
Performance_Score      0
Manager_ID             0
Join_Date              0
dtype: int64

In [10]:
#we see the Years_exp column have 326 null values
#we can replace the null values by 0
#means the the employee have 0 years of experience
data1['Years_Exp'].fillna(0,inplace=True)

/tmp/ipykernel_6926/3202779062.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1['Years_Exp'].fillna(0,inplace=True)

In [11]:
#check values are filled or not
data1.isnull().sum()

Employee_ID          0
Full_Name            0
Department           0
Monthly_Salary       0
Years_Exp            0
Office_Location      0
Performance_Score    0
Manager_ID           0
Join_Date            0
dtype: int64

In [ ]:
#null values are 0 means all null value are handelled

#Handelling Duplicates values
-> find duplicates

-> delete them

In [12]:
#check duplicate values
data1.duplicated().sum()

np.int64(600)

In [13]:
#there are 600 duplicate rows in data
#now delete the duplicates
data1.drop_duplicates(inplace=True)

In [14]:
#checking duplicates are deleted or not
data1.duplicated().sum()

np.int64(0)

In [15]:
#checking rows and columns
data1.shape

(2000, 9)

In [16]:
#check data again and do staistic calculations
data1.head()

,Employee_ID,Full_Name,Department,Monthly_Salary,Years_Exp,Office_Location,Performance_Score,Manager_ID,Join_Date
0,EMP-0152,Employee_151,Finance,4980.356928,38.0,Hybrid,5,MGR-4,2015-06-01
1,EMP-0754,Employee_753,HR,5988.381253,20.0,On-site,2,MGR-34,2017-01-23
2,EMP-1472,Employee_1471,Sales,3252.604294,30.0,Remote,1,MGR-24,2019-01-11
3,EMP-1232,Employee_1231,HR,4177.594228,6.0,Hybrid,5,MGR-7,2018-05-16
4,EMP-0022,Employee_21,Legal,273154.715607,35.0,Remote,1,MGR-13,2015-01-22

In [17]:
data1.describe()

       Monthly_Salary    Years_Exp  Performance_Score
count     2000.000000  2000.000000        2000.000000
mean     17528.790315    18.013000           2.984500
std      55669.821039    12.881102           1.432929
min       2040.176787     0.000000           1.000000
25%       4370.187392     6.000000           2.000000
50%       5044.817393    18.000000           3.000000
75%       5770.865215    30.000000           4.000000
max     353179.924727    40.000000           5.000000

#Data cleaning for second data

In [19]:
#importing data 2
data2=pd.read_excel("/content/3_Healthcare_Cleaning_Practice.xlsx")

In [20]:
#get first 5 rows
data2.head()

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
0,PT-0453,Patient_452,62,O,65.695565,36.600938,126,INS-9828,2025-01-19
1,PT-0071,Patient_70,81,O,66.817837,36.995776,131,INS-5819,2025-01-03
2,PT-0156,Patient_155,5,O,59.934299,36.790915,128,INS-1923,2025-01-07
3,PT-1479,Patient_1478,89,F,76.003233,36.912039,134,INS-1421,2025-03-03
4,PT-0308,Patient_307,39,O,62.876117,37.873569,138,INS-3626,2025-01-13

In [21]:
#get last 5 rows
data2.tail()

,Patient_ID,Patient_Name,Age,Gender,Heart_Rate,Body_Temp_C,Blood_Pressure_Sys,Insurance_ID,Last_Checkup
2595,PT-1391,Patient_1390,1,M,450.000000,36.672493,116,INS-9630,2025-02-27
2596,PT-1349,Patient_1348,85,O,70.755489,37.353741,134,INS-3252,2025-02-26
2597,PT-0112,Patient_111,54,M,74.202918,37.416936,123,INS-5483,2025-01-05
2598,PT-0301,NaN,83,O,63.195318,36.219781,140,INS-7665,2025-01-13
2599,PT-1225,Patient_1224,73,M,74.383926,36.310635,139,INS-3402,2025-02-21

In [22]:
#check null values
data2.isnull().sum()

Patient_ID              0
Patient_Name          171
Age                     0
Gender                  0
Heart_Rate              0
Body_Temp_C             0
Blood_Pressure_Sys      0
Insurance_ID            0
Last_Checkup            0
dtype: int64

In [25]:
#replace null values
data2['Patient_Name'].fillna("NoName",inplace=True)

/tmp/ipykernel_6926/2871875924.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data2['Patient_Name'].fillna("NoName",inplace=True)

In [26]:
#again check null values
data2.isnull().sum()

Patient_ID            0
Patient_Name          0
Age                   0
Gender                0
Heart_Rate            0
Body_Temp_C           0
Blood_Pressure_Sys    0
Insurance_ID          0
Last_Checkup          0
dtype: int64

In [27]:
#check duplicates
data2.duplicated().sum()

np.int64(600)

In [28]:
#delete duplicates
data2.drop_duplicates(inplace=True)

In [29]:
#again check duplicates
data2.duplicated().sum()

np.int64(0)

In [30]:
#now the data is clean
#we can do statistical analysis
#first check rows and columns
data2.shape

(2000, 9)

In [31]:
data2.describe()

               Age   Heart_Rate  Body_Temp_C  Blood_Pressure_Sys
count  2000.000000  2000.000000  2000.000000         2000.000000
mean     48.551500    77.805149    37.004269          124.900500
std      27.539981    46.596463     0.495560            8.901754
min       1.000000    47.730630    35.424255          110.000000
25%      25.000000    67.017407    36.670485          117.000000
50%      49.000000    72.249923    36.998417          125.000000
75%      73.000000    77.527227    37.354017          133.000000
max      95.000000   450.000000    38.853324          140.000000

#--------------------Now Both Data Data1 and Data2 has been cleand------------